name: CI

on: [pull_request, workflow_dispatch]

jobs:
  compile-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: compile tests
        run: |
          cd Projects/P2
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java

  test-ghost-move:
    needs: compile-tests
    run: |
      java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
